package instruments;
/*
 * DSO40.java
 *
 * Created on November 18, 2003, 3:30 PM
 */

/**
 *
 * @author  operator
 */

import javax.swing.*;
import networking.netConnect;

public class DSO40 extends javax.swing.JInternalFrame {
    private byte[] DSO40Armed = {0x03,0x03};    
    private byte[] DSO40CheckStatus = {0x03,0x05,0x00,0x00};    
    
    private netConnect con;
    private DSO40Waveform wave;
    private String[] sampleTime = {"40 MS/s","20 MS/s","10 MS/s","5 MS/s", "2,5 MS/s"};
    private double[] sampleScale ={25 * 1E-9, 50 * 1E-9, 100 * 1E-9, 200 * 1E-9, 400 * 1E-9};
    private double[] sampleVScale = {1.2, 2.4, 6.32};
    
    /** Creates new form DSO40 */
    public DSO40(netConnect c) {
        con = c;
        initComponents();
        wave = new DSO40Waveform(); 
        wave.updateScale(sampleVScale[0],0);
        wave.updateScale(sampleVScale[0],1);
        wave.updateScale(sampleVScale[0],2);
        wave.updateScale(sampleVScale[0],3);
        
        wave.updateTimeScale(sampleScale[0],0);
        wave.updateTimeScale(sampleScale[0],1);
        wave.updateTimeScale(sampleScale[0],2);
        wave.updateTimeScale(sampleScale[0],3);
        
        jSpinner1.setModel(new SpinnerListModel(sampleTime));
        jSpinner2.setModel(new SpinnerNumberModel(0.0,-5.0,5.0,0.01));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jSpinner2 = new javax.swing.JSpinner();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.TitledBorder("40MHZ Analog sample engine"));
        setMaximumSize(new java.awt.Dimension(400, 210));
        setMinimumSize(new java.awt.Dimension(400, 210));
        setPreferredSize(new java.awt.Dimension(400, 210));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBorder(new javax.swing.border.TitledBorder("Status"));
        jButton1.setText("RUN");
        jButton1.setMaximumSize(new java.awt.Dimension(81, 25));
        jButton1.setMinimumSize(new java.awt.Dimension(81, 25));
        jButton1.setPreferredSize(new java.awt.Dimension(81, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton1);

        jButton2.setText("STOP");
        jButton2.setMaximumSize(new java.awt.Dimension(81, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(81, 25));
        jButton2.setPreferredSize(new java.awt.Dimension(81, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton2);

        jButton7.setText("Testing");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton7);

        jButton8.setText("Wave");
        jButton8.setMaximumSize(new java.awt.Dimension(81, 25));
        jButton8.setMinimumSize(new java.awt.Dimension(81, 25));
        jButton8.setPreferredSize(new java.awt.Dimension(81, 25));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton8);

        add(jPanel2, java.awt.BorderLayout.EAST);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel4.setLayout(null);

        jPanel4.setBorder(new javax.swing.border.TitledBorder("Sampling/Memory"));
        jToggleButton6.setText("32k");
        buttonGroup4.add(jToggleButton6);
        jToggleButton6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jPanel4.add(jToggleButton6);
        jToggleButton6.setBounds(10, 55, 40, 25);

        jToggleButton7.setSelected(true);
        jToggleButton7.setText("64k");
        buttonGroup4.add(jToggleButton7);
        jToggleButton7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        jPanel4.add(jToggleButton7);
        jToggleButton7.setBounds(55, 55, 40, 25);

        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jPanel4.add(jSpinner1);
        jSpinner1.setBounds(10, 20, 75, 20);

        jPanel3.add(jPanel4);

        jPanel5.setLayout(null);

        jPanel5.setBorder(new javax.swing.border.TitledBorder("Trigger"));
        jToggleButton2.setSelected(true);
        jToggleButton2.setText("U");
        buttonGroup2.add(jToggleButton2);
        jToggleButton2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jPanel5.add(jToggleButton2);
        jToggleButton2.setBounds(10, 55, 40, 25);

        jToggleButton3.setText("D");
        buttonGroup2.add(jToggleButton3);
        jToggleButton3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jPanel5.add(jToggleButton3);
        jToggleButton3.setBounds(55, 55, 40, 25);

        jToggleButton4.setText("EXT");
        buttonGroup3.add(jToggleButton4);
        jToggleButton4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jPanel5.add(jToggleButton4);
        jToggleButton4.setBounds(145, 55, 40, 25);

        jToggleButton5.setText("BUS");
        buttonGroup3.add(jToggleButton5);
        jToggleButton5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jPanel5.add(jToggleButton5);
        jToggleButton5.setBounds(190, 55, 40, 25);

        jToggleButton9.setSelected(true);
        jToggleButton9.setText("INT");
        buttonGroup3.add(jToggleButton9);
        jToggleButton9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });

        jPanel5.add(jToggleButton9);
        jToggleButton9.setBounds(100, 55, 40, 25);

        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        jPanel5.add(jSpinner2);
        jSpinner2.setBounds(10, 20, 75, 20);

        jPanel3.add(jPanel5);

        add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jPanel6.setBorder(new javax.swing.border.TitledBorder("Voltage scale"));
        jPanel6.setMaximumSize(new java.awt.Dimension(60, 121));
        jPanel6.setMinimumSize(new java.awt.Dimension(60, 121));
        jPanel6.setPreferredSize(new java.awt.Dimension(60, 121));
        jRadioButton1.setText("5:1");
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jPanel6.add(jRadioButton1);

        jRadioButton2.setText("2:1");
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jPanel6.add(jRadioButton2);

        jRadioButton3.setSelected(true);
        jRadioButton3.setText("1:1");
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jPanel6.add(jRadioButton3);

        jRadioButton4.setText("1:5");
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jPanel6.add(jRadioButton4);

        add(jPanel6, java.awt.BorderLayout.WEST);

    }//GEN-END:initComponents

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        // Add your handling code here:
    }//GEN-LAST:event_jSpinner2StateChanged

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        // Add your handling code here:
        int i = 0;
        // find out current value
        for(i = 0; i < sampleTime.length; i++) {
            if(sampleTime[i].equals(jSpinner1.getValue()) == true)
                // set new sample time
                wave.updateTimeScale(sampleScale[i],0);
        }
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // Add your handling code here:
        wave.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Add your handling code here:
        int i = 0, p = 0,offset = 0;        
        byte[] rBytes = new byte[65536];
        byte[] tmp = new byte[1024];       
        
        // packet number hi byte
        DSO40CheckStatus[2] = 0x00;
        // packet number lo byte
        DSO40CheckStatus[3] = 0x00;
        // send status request
        con.netWrite(DSO40CheckStatus);
        // read server response
        String response = con.netRead();
        if(response.indexOf("OKreadDSO40") != -1) {
            for(i = 0;i < 64;i++) {
                // packet number hi byte
                DSO40CheckStatus[2] = (byte)((i & 0xFF00) << 8);
                // packet number lo byte
                DSO40CheckStatus[3] = (byte)((i + 1) & 0x00FF);
                // send packet request
                con.netWrite(DSO40CheckStatus);
                // read packet
                tmp = con.netReadPacket(1024);
                // put it in receive buffer
                for(p = 0;p < 1024;p++) {
                    rBytes[p + offset] = tmp[p];
                }
                // receive buffer offset increment
                offset += 1024;
            }
        }
                
        wave.updateData(rBytes);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        // get device ready
        con.netWrite(DSO40Armed);
        // read server response
        String response = con.netRead();
        //if(response.indexOf("OKarmedDSO40") != -1)
        //    con.setFlag();
        if(response.indexOf("OK") != -1) {
            //jButton4.setEnabled(false);
            // kill previous thread if exist
            //if(checkStatus != null)
            //    checkStatus = null;
            // start new thread
            //start();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jToggleButton5ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jToggleButton9ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jToggleButton7ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // Add your handling code here:
        wave.updateScale(sampleVScale[0], 0);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // Add your handling code here:
        wave.updateScale(sampleVScale[1], 0);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // Add your handling code here:
        wave.updateScale(sampleVScale[2], 0);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // Add your handling code here:
        
        // show testing dialog
        DSO40Testing test = new DSO40Testing(new javax.swing.JFrame(), true, con);
        test.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton9;
    // End of variables declaration//GEN-END:variables
    
}
