package instruments;
/*
 * DSO40Waveform.java
 *
 * Created on January 20, 2004, 5:36 PM
 */

/**
 *
 * @author  operator
 */

import oh3ebf.lib.gui.ScopePlot;
import javax.swing.*;
import oh3ebf.lib.gui.interfaces.PlotCursorInterface;

public class DSO40Waveform extends javax.swing.JFrame  implements PlotCursorInterface {
    private ScopePlot scope;
    private String[] vertScale = {"100 mV/div","200 mV/div","500 mV/div","1 V/div","2 V/div","5 V/div"};
    private double[] scaleVoltage = {0.8, 1.2, 4.0, 8.0, 16.0, 40.0};
    
    private String[] hScale = {"0.5 s/div","0.2 s/div","0.1 s/div","50 ms/div","20 ms/div","10 ms/div","5 ms/div","2 ms/div","1 ms/div",
    "0.5 ms/div","0.2 ms/div","0.1 ms/div","50 us/div","20 us/div","10 us/div","5 us/div","2 us/div","1 us/div","0.5 us/div","0.2 us/div",
    "0.1 us/div","50 ns/div","20 ns/div","10 ns/div"};

    private double[] hScaleTime = {0.5, 0.2, 0.1, 0.05, 0.02, 0.01, 0.005, 0.002, 0.001, 500 * 1E-6,
    200 * 1E-6, 100 * 1E-6, 50 * 1E-6, 20 * 1E-6, 10 * 1E-6, 5 * 1E-6, 2 * 1E-6, 1E-6, 500 * 1E-9, 
    200 * 1E-9, 100 * 1E-9, 50 * 1E-9, 20 * 1E-9, 10 * 1E-9};
    
    /** Creates new form DSO40Waveform */
    public DSO40Waveform() {
        initComponents();
        setSize(800,600);
        setLocationRelativeTo(null);
        
        // 
        //scope = new ScopePlot(4, ((PlotCursorInterface)this));
        //scope.setSize(jPanel23.getSize());        
        //jPanel23.add(scope, java.awt.BorderLayout.CENTER);
        
        /*
        jTabbedPane1.setTitleAt(0,"Marker");
        jTabbedPane1.setTitleAt(1,"Memory");
        
        jTabbedPane2.setTitleAt(0,"Channel");
        jTabbedPane2.setTitleAt(1,"Values");
        
        
        jSpinner1.setModel(new SpinnerListModel(vertScale));           
        jSpinner2.setModel(new SpinnerNumberModel(0.0,-20.0,20.0,0.01));
        jSpinner3.setModel(new SpinnerListModel(vertScale));
        jSpinner4.setModel(new SpinnerNumberModel(0.0,-20.0,20.0,0.01));
        jSpinner6.setModel(new SpinnerListModel(vertScale));
        jSpinner7.setModel(new SpinnerNumberModel(0.0,-20.0,20.0,0.01));
        jSpinner8.setModel(new SpinnerListModel(vertScale));
        jSpinner9.setModel(new SpinnerNumberModel(0.0,-20.0,20.0,0.01));

        
        jSpinner5.setModel(new SpinnerListModel(hScale));
*/
        
        //scope.setTimeScale(hScaleTime[0]);
        /*
        scope.setVoltageScale(0, scaleVoltage[0]);
        scope.setVoltageScale(1, scaleVoltage[0]);
        scope.setVoltageScale(2, scaleVoltage[0]);
        scope.setVoltageScale(3, scaleVoltage[0]);
        
        scope.setGndRef(0, 0.0D);
        scope.setGndRef(1, 0.0D);
        scope.setGndRef(2, 0.0D);
        scope.setGndRef(3, 0.0D);        
         **/
    }
    
    public void updateData(byte[] d) {
        // set new waveform
        //scope.setData(d);
    }
    
    public void updateScale(double v, int ch) {
        // set new sampling voltage scale to ch0
        //scope.setVoltageSampleScale(v, ch);
    }
    
    public void updateTimeScale(double s, int ch) {
        // set new sampling time scale
        //scope.setSamplingTimeScale(s,ch);
    }
    
    @Override
    public void cursorPositionRawValues(int x1, int x2, int y1, int y2) {
        
    }

    @Override
    public void cursorPositionScaledValues(double x1, double x2, double y1, double y2) {
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinner2 = new javax.swing.JSpinner();
        jPanel10 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jSpinner3 = new javax.swing.JSpinner();
        jSpinner4 = new javax.swing.JSpinner();
        jPanel16 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jSpinner6 = new javax.swing.JSpinner();
        jSpinner7 = new javax.swing.JSpinner();
        jPanel17 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jSpinner8 = new javax.swing.JSpinner();
        jSpinner9 = new javax.swing.JSpinner();
        jPanel18 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel11 = new javax.swing.JPanel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jPanel12 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel13 = new javax.swing.JPanel();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel19 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox();
        jPanel20 = new javax.swing.JPanel();
        jComboBox4 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jSpinner10 = new javax.swing.JSpinner();
        jSpinner11 = new javax.swing.JSpinner();
        jPanel22 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox6 = new javax.swing.JCheckBox();
        jSpinner12 = new javax.swing.JSpinner();
        jSpinner13 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel14 = new javax.swing.JPanel();
        jSpinner5 = new javax.swing.JSpinner();
        jPanel23 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Digital scope");
        setLocationByPlatform(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(new javax.swing.border.EtchedBorder());
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        jPanel9.setLayout(new java.awt.GridBagLayout());

        jPanel9.setBorder(new javax.swing.border.EtchedBorder());
        jLabel1.setText("Ch1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel9.add(jLabel1, gridBagConstraints);

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel9.add(jCheckBox1, gridBagConstraints);

        jSpinner1.setModel(new SpinnerListModel(vertScale));
        jSpinner1.setEnabled(false);
        jSpinner1.setPreferredSize(new java.awt.Dimension(100, 24));
        jSpinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner1StateChanged(evt);
            }
        });

        jPanel9.add(jSpinner1, new java.awt.GridBagConstraints());

        jSpinner2.setModel(new SpinnerNumberModel(0.0,-20.0,20.0,0.01));
        jSpinner2.setEnabled(false);
        jSpinner2.setPreferredSize(new java.awt.Dimension(100, 24));
        jSpinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner2StateChanged(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel9.add(jSpinner2, gridBagConstraints);

        jPanel7.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridBagLayout());

        jPanel10.setBorder(new javax.swing.border.EtchedBorder());
        jLabel2.setText("Ch2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel10.add(jLabel2, gridBagConstraints);

        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel10.add(jCheckBox2, gridBagConstraints);

        jSpinner3.setModel(new SpinnerListModel(vertScale));
        jSpinner3.setEnabled(false);
        jSpinner3.setPreferredSize(new java.awt.Dimension(100, 24));
        jSpinner3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner3StateChanged(evt);
            }
        });

        jPanel10.add(jSpinner3, new java.awt.GridBagConstraints());

        jSpinner4.setModel(new SpinnerNumberModel(0.0,-20.0,20.0,0.01));
        jSpinner4.setEnabled(false);
        jSpinner4.setPreferredSize(new java.awt.Dimension(100, 24));
        jSpinner4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner4StateChanged(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel10.add(jSpinner4, gridBagConstraints);

        jPanel7.add(jPanel10);

        jPanel16.setLayout(new java.awt.GridBagLayout());

        jPanel16.setBorder(new javax.swing.border.EtchedBorder());
        jLabel3.setText("Ch3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel16.add(jLabel3, gridBagConstraints);

        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel16.add(jCheckBox3, gridBagConstraints);

        jSpinner6.setModel(new SpinnerListModel(vertScale));
        jSpinner6.setEnabled(false);
        jSpinner6.setPreferredSize(new java.awt.Dimension(100, 24));
        jSpinner6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner6StateChanged(evt);
            }
        });

        jPanel16.add(jSpinner6, new java.awt.GridBagConstraints());

        jSpinner7.setModel(new SpinnerNumberModel(0.0,-20.0,20.0,0.01));
        jSpinner7.setEnabled(false);
        jSpinner7.setPreferredSize(new java.awt.Dimension(100, 24));
        jSpinner7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner7StateChanged(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel16.add(jSpinner7, gridBagConstraints);

        jPanel7.add(jPanel16);

        jPanel17.setLayout(new java.awt.GridBagLayout());

        jPanel17.setBorder(new javax.swing.border.EtchedBorder());
        jLabel4.setText("Ch4");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel17.add(jLabel4, gridBagConstraints);

        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel17.add(jCheckBox4, gridBagConstraints);

        jSpinner8.setModel(new SpinnerListModel(vertScale));
        jSpinner8.setEnabled(false);
        jSpinner8.setPreferredSize(new java.awt.Dimension(100, 24));
        jSpinner8.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner8StateChanged(evt);
            }
        });

        jPanel17.add(jSpinner8, new java.awt.GridBagConstraints());

        jSpinner9.setModel(new SpinnerNumberModel(0.0,-20.0,20.0,0.01));
        jSpinner9.setEnabled(false);
        jSpinner9.setPreferredSize(new java.awt.Dimension(100, 24));
        jSpinner9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner9StateChanged(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel17.add(jSpinner9, gridBagConstraints);

        jPanel7.add(jPanel17);

        jTabbedPane2.addTab("Channel", jPanel7);

        jTabbedPane2.addTab("Values", jPanel18);

        jPanel1.add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel4.setBorder(new javax.swing.border.EtchedBorder());
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel15.setLayout(new java.awt.GridBagLayout());

        jPanel6.setLayout(new java.awt.GridLayout(2, 2));

        jPanel6.setBorder(new javax.swing.border.TitledBorder(null, "Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10)));
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("None");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jPanel6.add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("X");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jPanel6.add(jRadioButton2);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("Y");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jPanel6.add(jRadioButton3);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("XY");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jPanel6.add(jRadioButton4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        jPanel15.add(jPanel6, gridBagConstraints);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));

        jPanel11.setBorder(new javax.swing.border.TitledBorder(null, "Mode", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10)));
        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setSelected(true);
        jRadioButton5.setText("Independent");
        jPanel11.add(jRadioButton5);

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setText("Paired");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jPanel11.add(jRadioButton6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel15.add(jPanel11, gridBagConstraints);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel12.setBorder(new javax.swing.border.TitledBorder(null, "M1 X source", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10)));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel12.add(jComboBox1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel15.add(jPanel12, gridBagConstraints);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel13.setBorder(new javax.swing.border.TitledBorder(null, "M2 X source", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10)));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jPanel13.add(jComboBox2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel15.add(jPanel13, gridBagConstraints);

        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel19.setBorder(new javax.swing.border.TitledBorder(null, "M1 Y source", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10)));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jPanel19.add(jComboBox3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel15.add(jPanel19, gridBagConstraints);

        jPanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel20.setBorder(new javax.swing.border.TitledBorder(null, "M2 Y source", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 10)));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jPanel20.add(jComboBox4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel15.add(jPanel20, gridBagConstraints);

        jPanel3.add(jPanel15, java.awt.BorderLayout.NORTH);

        jTabbedPane1.addTab("Cursors", jPanel3);

        jPanel5.setLayout(new java.awt.GridBagLayout());

        jPanel21.setLayout(new java.awt.GridBagLayout());

        jPanel21.setBorder(new javax.swing.border.EtchedBorder());
        jLabel5.setText("M1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel21.add(jLabel5, gridBagConstraints);

        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel21.add(jCheckBox5, gridBagConstraints);

        jSpinner10.setPreferredSize(new java.awt.Dimension(100, 24));
        jSpinner10.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner10StateChanged(evt);
            }
        });

        jPanel21.add(jSpinner10, new java.awt.GridBagConstraints());

        jSpinner11.setPreferredSize(new java.awt.Dimension(100, 24));
        jSpinner11.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner11StateChanged(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel21.add(jSpinner11, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        jPanel5.add(jPanel21, gridBagConstraints);

        jPanel22.setLayout(new java.awt.GridBagLayout());

        jPanel22.setBorder(new javax.swing.border.EtchedBorder());
        jLabel6.setText("M2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        jPanel22.add(jLabel6, gridBagConstraints);

        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel22.add(jCheckBox6, gridBagConstraints);

        jSpinner12.setPreferredSize(new java.awt.Dimension(100, 24));
        jSpinner12.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner12StateChanged(evt);
            }
        });

        jPanel22.add(jSpinner12, new java.awt.GridBagConstraints());

        jSpinner13.setPreferredSize(new java.awt.Dimension(100, 24));
        jSpinner13.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner13StateChanged(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel22.add(jSpinner13, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel5.add(jPanel22, gridBagConstraints);

        jTabbedPane1.addTab("Memory", jPanel5);

        jPanel4.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel4, java.awt.BorderLayout.EAST);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel8.setLayout(new java.awt.BorderLayout());

        jScrollBar1.setMaximum(65000);
        jScrollBar1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        jScrollBar1.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                jScrollBar1AdjustmentValueChanged(evt);
            }
        });

        jPanel8.add(jScrollBar1, java.awt.BorderLayout.CENTER);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jSpinner5.setModel(new SpinnerListModel(hScale));
        jSpinner5.setPreferredSize(new java.awt.Dimension(100, 24));
        jSpinner5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner5StateChanged(evt);
            }
        });

        jPanel14.add(jSpinner5);

        jPanel8.add(jPanel14, java.awt.BorderLayout.SOUTH);

        jPanel2.add(jPanel8, java.awt.BorderLayout.SOUTH);

        jPanel23.setLayout(new java.awt.BorderLayout());

        jPanel2.add(jPanel23, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuItem1.setText("Close");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }//GEN-END:initComponents

    private void jSpinner13StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner13StateChanged
        // Add your handling code here:
    }//GEN-LAST:event_jSpinner13StateChanged

    private void jSpinner12StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner12StateChanged
        // Add your handling code here:
    }//GEN-LAST:event_jSpinner12StateChanged

    private void jSpinner11StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner11StateChanged
        // Add your handling code here:
    }//GEN-LAST:event_jSpinner11StateChanged

    private void jSpinner10StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner10StateChanged
        // Add your handling code here:
    }//GEN-LAST:event_jSpinner10StateChanged

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // XY-cursors
        scope.setCursorMode(3);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // Y-cursors
        scope.setCursorMode(2);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // X-cursors
        scope.setCursorMode(1);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // Add your handling code here:
        // no cursors
        scope.setCursorMode(0);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // close dialog
        setVisible(false);
        dispose();            
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // Enabling ch 3
        if(jCheckBox4.isSelected() == true) {
            // enable controls
            jSpinner8.setEnabled(true);
            jSpinner9.setEnabled(true);
            scope.setChActive(3, true);
        } else {
            // disable controls
            jSpinner8.setEnabled(false);
            jSpinner9.setEnabled(false);
            scope.setChActive(3, false);
        }        
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // Enabling ch 2
        if(jCheckBox3.isSelected() == true) {
            // enable controls
            jSpinner6.setEnabled(true);
            jSpinner7.setEnabled(true);
            scope.setChActive(2, true);
        } else {
            // disable controls
            jSpinner6.setEnabled(false);
            jSpinner7.setEnabled(false);
            scope.setChActive(2, false);
        }        
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jSpinner9StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner9StateChanged
    try {
        // set gnd reference value to ch4
        scope.setGndRef(3, Double.parseDouble((jSpinner9.getValue().toString())));        
    } catch(NumberFormatException e) {
        
    }
    }//GEN-LAST:event_jSpinner9StateChanged

    private void jSpinner8StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner8StateChanged
        // Add your handling code here:
        int i = 0;
        // evaluate voltage scale value
        for(i = 0;i < vertScale.length;i++) {
            if(vertScale[i].equals(jSpinner8.getValue())) {
                // set voltage scale to ch4
                //scope.setVoltageScale(scaleVoltage[i], 3);
            }
        }        
    }//GEN-LAST:event_jSpinner8StateChanged

    private void jSpinner7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner7StateChanged
        // Add your handling code here:
        // set gnd reference value to ch3
        //scope.setGndRef(Double.parseDouble((jSpinner7.getValue().toString())), 2);        
    }//GEN-LAST:event_jSpinner7StateChanged

    private void jSpinner6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner6StateChanged
        // Add your handling code here:
        int i = 0;
        // evaluate voltage scale value
        for(i = 0;i < vertScale.length;i++) {
            if(vertScale[i].equals(jSpinner6.getValue())) {
                // set voltage scale to ch3
                //scope.setVoltageScale(scaleVoltage[i], 2);
            }
        }        
    }//GEN-LAST:event_jSpinner6StateChanged

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // Enabling ch 1
        if(jCheckBox2.isSelected() == true) {
            // enable controls
            jSpinner3.setEnabled(true);
            jSpinner4.setEnabled(true);
            scope.setChActive(1, true);
        } else {
            // disable controls
            jSpinner3.setEnabled(false);
            jSpinner4.setEnabled(false);
            scope.setChActive(1, false);
        }        
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jSpinner4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner4StateChanged
        // Add your handling code here:
        // set gnd reference value to ch1
        //scope.setGndRef(Double.parseDouble((jSpinner4.getValue().toString())), 1);        
    }//GEN-LAST:event_jSpinner4StateChanged

    private void jSpinner3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner3StateChanged
        // Add your handling code here:
        int i = 0;
        // evaluate voltage scale value
        for(i = 0;i < vertScale.length;i++) {
            if(vertScale[i].equals(jSpinner3.getValue())) {
                // set voltage scale to ch1
                //scope.setVoltageScale(scaleVoltage[i], 1);
            }
        }        
    }//GEN-LAST:event_jSpinner3StateChanged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // Enabling ch 1
        if(jCheckBox1.isSelected() == true) {
            // enable controls
            jSpinner1.setEnabled(true);
            jSpinner2.setEnabled(true);
            scope.setChActive(0, true);
            
        } else {
            // disable controls
            jSpinner1.setEnabled(false);
            jSpinner2.setEnabled(false);
            scope.setChActive(0, false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jSpinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner2StateChanged
        // set gnd reference value to ch0
        scope.setGndRef(0, Double.parseDouble((jSpinner2.getValue().toString())));
    }//GEN-LAST:event_jSpinner2StateChanged

    private void jSpinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner1StateChanged
        int i = 0;

        // evaluate voltage scale value
        for(i = 0;i < vertScale.length;i++) {
            if(vertScale[i].equals(jSpinner1.getValue())) {
                // set voltage scale to ch0
                //scope.setVoltageScale(scaleVoltage[i], 0);
            }
        }
    }//GEN-LAST:event_jSpinner1StateChanged

    private void jSpinner5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner5StateChanged
        int i = 0;
        
        // find out current time/div value
        for(i = 0; i < hScale.length; i++) {
            if(hScale[i].equals(jSpinner5.getValue()) == true)
                // set new one
                scope.setTimeScale(hScaleTime[i]);
        }                
    }//GEN-LAST:event_jSpinner5StateChanged

    private void jScrollBar1AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_jScrollBar1AdjustmentValueChanged
        // Add your handling code here:
        //scope.setOffset(jScrollBar1.getValue());
    }//GEN-LAST:event_jScrollBar1AdjustmentValueChanged
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
            
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner10;
    private javax.swing.JSpinner jSpinner11;
    private javax.swing.JSpinner jSpinner12;
    private javax.swing.JSpinner jSpinner13;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    private javax.swing.JSpinner jSpinner7;
    private javax.swing.JSpinner jSpinner8;
    private javax.swing.JSpinner jSpinner9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
    
}
