package instruments;

import networking.netConnect;
/*
 * LA40Trigger.java
 *
 * Created on January 30, 2004, 8:20 PM
 */

/**
 *
 * @author  operator
 */
public class LA40Trigger extends javax.swing.JFrame {
    private byte[] LA40TrigPattern = {0x02,0x02,0x00,'x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','\0'};
    
    private LA40TriggerSelector select;
    private byte[] pod0 = {'x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','\0'};
    private byte[] pod1 = {'x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','\0'};
    private byte[] pod2 = {'x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','\0'};
    private byte[] pod3 = {'x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','x','\0'};
    private int podNumber = 0;
    private netConnect con;
    
    /** Creates new form LA40Trigger */
    public LA40Trigger(netConnect c) {
        con = c;
        initComponents();
        setSize(600,250);
        select = new LA40TriggerSelector();
        jPanel3.add(select, java.awt.BorderLayout.CENTER);
    }
    
    public void setActive(boolean[] p) {
        // update current pod active status
        if(p[0] == true)
            jRadioButton1.setEnabled(true);
        else
            jRadioButton1.setEnabled(false);
        
        if(p[1] == true)
            jRadioButton2.setEnabled(true);
        else
            jRadioButton2.setEnabled(false);
        
        if(p[2] == true)
            jRadioButton3.setEnabled(true);
        else
            jRadioButton3.setEnabled(false);
        
        if(p[3] == true)
            jRadioButton4.setEnabled(true);
        else
            jRadioButton4.setEnabled(false);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setTitle("Trigger pattern selection");
        setLocationRelativeTo(this);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBorder(new javax.swing.border.TitledBorder("Pods"));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Pod 0");
        buttonGroup1.add(jRadioButton1);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButton1);

        jRadioButton2.setText("Pod 1");
        buttonGroup1.add(jRadioButton2);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButton2);

        jRadioButton3.setText("Pod 2");
        buttonGroup1.add(jRadioButton3);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButton3);

        jRadioButton4.setText("Pod 3");
        buttonGroup1.add(jRadioButton4);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButton4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Apply");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton1);

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.add(jButton2);

        jPanel3.add(jPanel2, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // Add your handling code here:
        // save current pattern
        switch(podNumber) {
            case 0:
                pod0 = select.getTrigPattern();
                break;
            case 1:
                pod1 = select.getTrigPattern();
                break;
            case 2:
                pod2 = select.getTrigPattern();
                break;
            case 3:
                pod3 = select.getTrigPattern();
                break;
        }
        
        // set current pod number
        podNumber = 3;
        // update display
        select.setTrigPattern(pod3);        
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // Add your handling code here:
        // save current pattern
        switch(podNumber) {
            case 0:
                pod0 = select.getTrigPattern();
                break;
            case 1:
                pod1 = select.getTrigPattern();
                break;
            case 2:
                pod2 = select.getTrigPattern();
                break;
            case 3:
                pod3 = select.getTrigPattern();
                break;
        }
        
        // set current pod number
        podNumber = 2;
        // update display
        select.setTrigPattern(pod2);        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // Add your handling code here:
        // save current pattern
        switch(podNumber) {
            case 0:
                pod0 = select.getTrigPattern();
                break;
            case 1:
                pod1 = select.getTrigPattern();
                break;
            case 2:
                pod2 = select.getTrigPattern();
                break;
            case 3:
                pod3 = select.getTrigPattern();
                break;
        }
        
        // set current pod number
        podNumber = 1;
        // update display
        select.setTrigPattern(pod1);        
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // Add your handling code here:
        // save current pattern
        switch(podNumber) {
            case 0:
                pod0 = select.getTrigPattern();
                break;
            case 1:
                pod1 = select.getTrigPattern();
                break;
            case 2:
                pod2 = select.getTrigPattern();
                break;
            case 3:
                pod3 = select.getTrigPattern();
                break;
        }
        
        // set current pod number
        podNumber = 0;
        // update display
        select.setTrigPattern(pod0);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Add your handling code here:
        // close dialog
        setVisible(false);
        dispose();        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        int i = 0;
        // pod 0
        if(jRadioButton1.isEnabled() == true) {
            // set ramcard number
            LA40TrigPattern[2] = 0x00;
            // copy trigpattern to message
            for(i = 0; i < 16;i++)
                LA40TrigPattern[i + 3] = pod0[i];
            // send trigger pattern
            con.netWrite(LA40TrigPattern);
            // read server response
            String response = con.netRead();
            if(response.indexOf("OK") != -1) {
                
            }
        }
        
        // pod 1
        if(jRadioButton2.isEnabled() == true) {
            // set ramcard number
            LA40TrigPattern[2] = 0x01;
            // copy trigpattern to message
            for(i = 0; i < 16;i++)
                LA40TrigPattern[i + 3] = pod1[i];
            // send trigger pattern
            con.netWrite(LA40TrigPattern);
            // read server response
            String response = con.netRead();
            if(response.indexOf("OK") != -1) {
                
            }
        }
        
        // pod 2
        if(jRadioButton3.isEnabled() == true) {
            // set ramcard number
            LA40TrigPattern[2] = 0x02;
            // copy trigpattern to message
            for(i = 0; i < 16;i++)
                LA40TrigPattern[i + 3] = pod2[i];
            // send trigger pattern
            con.netWrite(LA40TrigPattern);
            // read server response
            String response = con.netRead();
            if(response.indexOf("OK") != -1) {
                
            }
        }
        
        // pod 3
        if(jRadioButton4.isEnabled() == true) {
            // set ramcard number
            LA40TrigPattern[2] = 0x03;
            // copy trigpattern to message
            for(i = 0; i < 16;i++)
                LA40TrigPattern[i + 3] = pod3[i];
            // send trigger pattern
            con.netWrite(LA40TrigPattern);
            // read server response
            String response = con.netRead();
            if(response.indexOf("OK") != -1) {
                
            }
        }    
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    //    new LA40Trigger().show();
    //}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
    
}
