package instruments;

import networking.netCommand;
/*
 * LA40Testing.java
 *
 * Created on January 7, 2004, 6:42 PM
 */

/**
 *
 * @author  operator
 */

public class LA40Testing extends javax.swing.JDialog {
   
    private String testText = "Line set to ";
    private int testSelection = 1;
    private int testValue = 0;
    private netCommand ycon;
    
    /** Creates new form LA40Testing */
    public LA40Testing(java.awt.Frame parent, boolean modal, netCommand c) {
        super(parent, modal);
        ycon = c;
        
        initComponents();        
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);   
        RamTestItems();
        jTabbedPane1.setTitleAt(0,"Counter card");
        jTabbedPane1.setTitleAt(1,"RAM card");       
    }
    
    private Object makeObj(final String item) {
        return new Object() { 
            public String toString() { 
                return item;
            }
        };
    }

    private void dividerTestItems() {
        // destroy previous list
        jComboBox1.removeAllItems();
        // add divider selection list
        jComboBox1.addItem(makeObj("1666.6kHz"));
        jComboBox1.addItem(makeObj("1785.6kHz"));
        jComboBox1.addItem(makeObj("1923.0kHz"));
        jComboBox1.addItem(makeObj("2083.2kHz"));
        jComboBox1.addItem(makeObj("2272.6kHz"));
        jComboBox1.addItem(makeObj("2499.9kHz"));
        jComboBox1.addItem(makeObj("2777.7kHz"));
        jComboBox1.addItem(makeObj("3124.9kHz"));
        jComboBox1.addItem(makeObj("3571.2kHz"));
        jComboBox1.addItem(makeObj("4166.5kHz"));
        jComboBox1.addItem(makeObj("4999.8kHz"));
        jComboBox1.addItem(makeObj("6249.8kHz"));
        jComboBox1.addItem(makeObj("8333.0kHz"));
        jComboBox1.addItem(makeObj("12.499MHz"));
        jComboBox1.addItem(makeObj("24.999MHz"));        
    }
    
    private void clkTestItems() {
        // destroy previous list
        jComboBox1.removeAllItems();
        // add divider selection list        
        jComboBox1.addItem(makeObj("50MHz"));
        jComboBox1.addItem(makeObj("25MHz"));
        jComboBox1.addItem(makeObj("Divider"));
        jComboBox1.addItem(makeObj("External"));
    }

    private void RamTestItems() {
        // destroy previous list
        jComboBox2.removeAllItems();
        // add divider selection list        
        jComboBox2.addItem(makeObj("0"));
        jComboBox2.addItem(makeObj("1"));
        //jComboBox2.addItem(makeObj("2"));
        //jComboBox2.addItem(makeObj("3"));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLocationRelativeTo(this);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jTabbedPane1.setBorder(new javax.swing.border.TitledBorder("Test selection"));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("RESET");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButton1);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("CLR");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButton2);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("STEP_EN");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButton3);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("D8");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButton4);

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("TRIG_CLR");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButton5);

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("MEM_SIZE");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButton6);

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("U11/U12 ENABLE");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButton7);

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("COUNTER STEP");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButton8);

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setText("COUNTER CLK SELECT");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButton9);

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setText("TRIGGER SELECT");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButton10);

        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setText("U11 DIVIDER");
        jRadioButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton11ActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButton11);

        buttonGroup1.add(jRadioButton12);
        jRadioButton12.setText("U12 DIVIDER");
        jRadioButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton12ActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButton12);

        buttonGroup1.add(jRadioButton13);
        jRadioButton13.setText("STATUS REGISTER");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        jPanel1.add(jRadioButton13);

        jTabbedPane1.addTab("tab1", jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));

        buttonGroup1.add(jRadioButton14);
        jRadioButton14.setText("RAM OE 0");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });

        jPanel2.add(jRadioButton14);

        buttonGroup1.add(jRadioButton15);
        jRadioButton15.setText("INPUT ENABLE 0");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });

        jPanel2.add(jRadioButton15);

        buttonGroup1.add(jRadioButton16);
        jRadioButton16.setText("RAM OE 1");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });

        jPanel2.add(jRadioButton16);

        buttonGroup1.add(jRadioButton17);
        jRadioButton17.setText("INPUT ENABLE 1");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });

        jPanel2.add(jRadioButton17);

        buttonGroup1.add(jRadioButton18);
        jRadioButton18.setText("READ INPUT");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });

        jPanel2.add(jRadioButton18);

        buttonGroup1.add(jRadioButton19);
        jRadioButton19.setText("READ EXT INPUT");
        jRadioButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton19ActionPerformed(evt);
            }
        });

        jPanel2.add(jRadioButton19);

        jTabbedPane1.addTab("tab2", jPanel2);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.WEST);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel4.add(jTextArea1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jPanel7.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1.setToolTipText("Select test data");
        jComboBox1.setPreferredSize(new java.awt.Dimension(100, 25));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jPanel7.add(jComboBox1);

        jComboBox2.setToolTipText("Ram card number");
        jComboBox2.setPreferredSize(new java.awt.Dimension(40, 25));
        jPanel7.add(jComboBox2);

        jPanel6.add(jPanel7);

        jButton1.setText("Run Test");
        jButton1.setToolTipText("Run selected test");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel5.add(jButton1);

        jButton2.setText("Close");
        jButton2.setToolTipText("Close window");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel5.add(jButton2);

        jPanel6.add(jPanel5);

        jPanel3.add(jPanel6, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // Add your handling code here:
        testValue = jComboBox1.getSelectedIndex();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        switch(testSelection) {
            case 1:
                // run reset test case
                if(testValue == 0)
                    testValue = ycon.LA40TestExec(1, true, (byte)0);                    
                else                    
                    testValue = ycon.LA40TestExec(1, false, (byte)0);
                break;
            case 2:
                // run clr test case
                if(testValue == 0)
                    testValue = ycon.LA40TestExec(2, true, (byte)0);
                else
                    testValue = ycon.LA40TestExec(2, false, (byte)0);                
                break;
            case 3:
                // run step enable test case
                if(testValue == 0)
                    testValue = ycon.LA40TestExec(3, false, (byte)0);
                else
                    testValue = ycon.LA40TestExec(3, true, (byte)0);                
                break;
            case 4:
                // run D8 test case
                if(testValue == 0)
                    testValue = ycon.LA40TestExec(4, true, (byte)0);
                else
                    testValue = ycon.LA40TestExec(4, false, (byte)0);                
                break;
            case 5:
                // run trig clear test case
                if(testValue == 0)
                    testValue = ycon.LA40TestExec(5, true, (byte)0);
                else
                    testValue = ycon.LA40TestExec(5, false, (byte)0);                
                break;
            case 6:
                // run memory size test case
                if(testValue == 0)
                    testValue = ycon.LA40TestExec(6, false, (byte)0);
                else
                    testValue = ycon.LA40TestExec(6, true, (byte)0);                
                break;
            case 7:
                // run divider enable test case
                if(testValue == 0)
                    testValue = ycon.LA40TestExec(7, false, (byte)0);
                else
                    testValue = ycon.LA40TestExec(7, true, (byte)0);                                
                break;
            case 8:
                // run step line enable test case
                if(testValue == 0)
                    testValue = ycon.LA40TestExec(8, true, (byte)0);
                else
                    testValue = ycon.LA40TestExec(8, false, (byte)0);
                break;
            case 9:
                // run clk select test case                                
                ycon.LA40TestExec(9, false, (byte)jComboBox1.getSelectedIndex());
                break;
            case 10:
                // run trigger selection test case
                if(testValue == 0)
                    testValue = ycon.LA40TestExec(10, true, (byte)0);
                else
                    testValue = ycon.LA40TestExec(10, false, (byte)0);
                break;
            case 11:
                // run U11 test case                
                ycon.LA40TestExec(11, false, (byte)jComboBox1.getSelectedIndex());
                break;
            case 12:
                // run U12 test case
                ycon.LA40TestExec(12, false, (byte)jComboBox1.getSelectedIndex());
                break;
            case 13:
                // run status reading test case                
                testValue = ycon.LA40TestExec(13, false, (byte)0);
                break;
            case 14:
                // run RAM OE test case                           
                if(testValue == 0)
                    testValue = ycon.LA40TestExec(14, true, (byte)jComboBox2.getSelectedIndex());
                else
                    testValue = ycon.LA40TestExec(14, false, (byte)jComboBox2.getSelectedIndex());
                break;                                
            case 15:
                // run RAM input enable test case
                if(testValue == 0)
                    testValue = ycon.LA40TestExec(15, true, (byte)jComboBox2.getSelectedIndex());
                else
                    testValue = ycon.LA40TestExec(15, false, (byte)jComboBox2.getSelectedIndex());        
                break;
            case 16:
                // run RAM OE extension test case
                if(testValue == 0)
                    testValue = ycon.LA40TestExec(16, true, (byte)jComboBox2.getSelectedIndex());
                else
                    testValue = ycon.LA40TestExec(16, false, (byte)jComboBox2.getSelectedIndex());                
                break;
            case 17:
                // run RAM input extension enable test case
                if(testValue == 0)
                    testValue = ycon.LA40TestExec(17, true, (byte)jComboBox2.getSelectedIndex());
                else
                    testValue = ycon.LA40TestExec(17, false, (byte)jComboBox2.getSelectedIndex());                      
                break;
            case 18:
                // run input value test case
                testValue = ycon.LA40TestExec(18, false, (byte)0);
                break;
            case 19:
                // run input value extension test case
                testValue = ycon.LA40TestExec(19, false, (byte)0);
                break;
        }
        
        // write test result to screen
        jTextArea1.append(testText + testValue);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton19ActionPerformed
        // Add your handling code here:
        // set test selection to extension card input reading
        testSelection = 19;        
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(true);
    }//GEN-LAST:event_jRadioButton19ActionPerformed

    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
        // Add your handling code here:
        // set test selection to input reading
        testSelection = 18;      
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(true);
    }//GEN-LAST:event_jRadioButton18ActionPerformed

    private void jRadioButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        // Add your handling code here:
        // set test selection to input 1 enable line
        testSelection = 17;      
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(true);
    }//GEN-LAST:event_jRadioButton17ActionPerformed

    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        // Add your handling code here:
        // set test selection to RAM 1 OE line
        testSelection = 16;       
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(true);
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        // Add your handling code here:
        // set test selection to input 0 enable line
        testSelection = 15;        
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(true);
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // Add your handling code here:
        // set test selection to RAM 0 OE line
        testSelection = 14;     
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(true);
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        // Add your handling code here:
        // set test selection to status register reading
        testSelection = 13;      
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    private void jRadioButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton12ActionPerformed
        // Add your handling code here:
        // set test selection to U12 divider testing
        testSelection = 12;
        dividerTestItems();
        jComboBox1.setEnabled(true);
        jComboBox2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton12ActionPerformed

    private void jRadioButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton11ActionPerformed
        // Add your handling code here:
        // set test selection to U11 divider testing
        testSelection = 11;    
        dividerTestItems();
        jComboBox1.setEnabled(true);
        jComboBox2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton11ActionPerformed

    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // Add your handling code here:
        // set test selection to trigger select line
        testSelection = 10;        
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // Add your handling code here:
        // set test selection to counter clk select line
        testSelection = 9;        
        clkTestItems();
        jComboBox1.setEnabled(true);
        jComboBox2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton9ActionPerformed

    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // Add your handling code here:
        // set test selection to counter step line
        testSelection = 8;        
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton8ActionPerformed

    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // Add your handling code here:
        // set test selection to U11/U12 enable line
        testSelection = 7;     
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // Add your handling code here:
        // set test selection to memory size line
        testSelection = 6;     
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // Add your handling code here:
        // set test selection to trigger clr line
        testSelection = 5;   
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // Add your handling code here:
        // set test selection to D8 line
        testSelection = 4;        
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // Add your handling code here:
        // set test selection to step enable line
        testSelection = 3;       
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // Add your handling code here:
        // set test selection to clr line
        testSelection = 2;     
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // Add your handling code here:
        // set test selection to reset line
        testSelection = 1;
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Add your handling code here:
        // close dialog
        setVisible(false);
        dispose();        
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        new LA40Testing(new javax.swing.JFrame(), true).show();
//    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
