package instruments;
/*
 * LA40LabelSelector.java
 *
 * Created on March 21, 2004, 5:29 PM
 */

/**
 *
 * @author  operator
 */


public class LA40LabelSelector extends javax.swing.JPanel {
    private int mask = 0x0000;
    
    /** Creates new form LA40LabelSelector */
    public LA40LabelSelector() {
        initComponents();
    }
    
    public int getMask() {
        return(mask);
    }
    
    public void setMask(int m) {
        mask = m;
        
        // bit 0
        if((mask & 0x0001) == 0x0001)
            jToggleButton16.setSelected(true);
        else
            jToggleButton16.setSelected(false);
        
        // bit 1
        if((mask & 0x0002) == 0x0002)
            jToggleButton15.setSelected(true);
        else
            jToggleButton15.setSelected(false);
        
        // bit 2
        if((mask & 0x0004) == 0x0004)
            jToggleButton14.setSelected(true);
        else
            jToggleButton14.setSelected(false);
        
        // bit 3
        if((mask & 0x0008) == 0x0008)
            jToggleButton13.setSelected(true);
        else
            jToggleButton13.setSelected(false);
        
        // bit 4
        if((mask & 0x0010) == 0x0010)
            jToggleButton12.setSelected(true);
        else
            jToggleButton12.setSelected(false);
        
        // bit 5
        if((mask & 0x0020) == 0x0020)
            jToggleButton11.setSelected(true);
        else
            jToggleButton11.setSelected(false);
        
        // bit 6
        if((mask & 0x0040) == 0x0040)
            jToggleButton10.setSelected(true);
        else
            jToggleButton10.setSelected(false);
        
        // bit 7
        if((mask & 0x0080) == 0x0080)
            jToggleButton9.setSelected(true);
        else
            jToggleButton9.setSelected(false);
        
        // bit 8
        if((mask & 0x0100) == 0x0100)
            jToggleButton8.setSelected(true);
        else
            jToggleButton8.setSelected(false);
        
        // bit 9
        if((mask & 0x0200) == 0x0200)
            jToggleButton7.setSelected(true);
        else
            jToggleButton7.setSelected(false);
        
        // bit 10
        if((mask & 0x0400) == 0x0400)
            jToggleButton6.setSelected(true);
        else
            jToggleButton6.setSelected(false);
        
        // bit 11
        if((mask & 0x0800) == 0x0800)
            jToggleButton5.setSelected(true);
        else
            jToggleButton5.setSelected(false);
        
        // bit 12
        if((mask & 0x1000) == 0x1000)
            jToggleButton4.setSelected(true);
        else
            jToggleButton4.setSelected(false);
        
        // bit 13
        if((mask & 0x2000) == 0x2000)
            jToggleButton3.setSelected(true);
        else
            jToggleButton3.setSelected(false);
        
        // bit 14
        if((mask & 0x4000) == 0x4000)
            jToggleButton2.setSelected(true);
        else
            jToggleButton2.setSelected(false);
        
        // bit 15
        if((mask & 0x8000) == 0x8000)
            jToggleButton1.setSelected(true);
        else
            jToggleButton1.setSelected(false);
    }
    
    public void setActive(boolean p) {
        // update pod active information
        jToggleButton1.setEnabled(p);
        jToggleButton2.setEnabled(p);
        jToggleButton3.setEnabled(p);
        jToggleButton4.setEnabled(p);
        jToggleButton5.setEnabled(p);
        jToggleButton6.setEnabled(p);
        jToggleButton7.setEnabled(p);
        jToggleButton8.setEnabled(p);
        jToggleButton9.setEnabled(p);
        jToggleButton10.setEnabled(p);
        jToggleButton11.setEnabled(p);
        jToggleButton12.setEnabled(p);
        jToggleButton13.setEnabled(p);
        jToggleButton14.setEnabled(p);
        jToggleButton15.setEnabled(p);
        jToggleButton16.setEnabled(p);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();

        setBorder(new javax.swing.border.TitledBorder("Pod"));
        jToggleButton1.setText("15");
        jToggleButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        add(jToggleButton1);

        jToggleButton2.setText("14");
        jToggleButton2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        add(jToggleButton2);

        jToggleButton3.setText("13");
        jToggleButton3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        add(jToggleButton3);

        jToggleButton4.setText("12");
        jToggleButton4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        add(jToggleButton4);

        jToggleButton5.setText("11");
        jToggleButton5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        add(jToggleButton5);

        jToggleButton6.setText("10");
        jToggleButton6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        add(jToggleButton6);

        jToggleButton7.setText("9");
        jToggleButton7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton7.setMaximumSize(new java.awt.Dimension(26, 26));
        jToggleButton7.setMinimumSize(new java.awt.Dimension(26, 26));
        jToggleButton7.setPreferredSize(new java.awt.Dimension(26, 26));
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        add(jToggleButton7);

        jToggleButton8.setText("8");
        jToggleButton8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton8.setMaximumSize(new java.awt.Dimension(26, 26));
        jToggleButton8.setMinimumSize(new java.awt.Dimension(26, 26));
        jToggleButton8.setPreferredSize(new java.awt.Dimension(26, 26));
        jToggleButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton8ActionPerformed(evt);
            }
        });

        add(jToggleButton8);

        jToggleButton9.setText("7");
        jToggleButton9.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton9.setMaximumSize(new java.awt.Dimension(26, 26));
        jToggleButton9.setMinimumSize(new java.awt.Dimension(26, 26));
        jToggleButton9.setPreferredSize(new java.awt.Dimension(26, 26));
        jToggleButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton9ActionPerformed(evt);
            }
        });

        add(jToggleButton9);

        jToggleButton10.setText("6");
        jToggleButton10.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton10.setMaximumSize(new java.awt.Dimension(26, 26));
        jToggleButton10.setMinimumSize(new java.awt.Dimension(26, 26));
        jToggleButton10.setPreferredSize(new java.awt.Dimension(26, 26));
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });

        add(jToggleButton10);

        jToggleButton11.setText("5");
        jToggleButton11.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton11.setMaximumSize(new java.awt.Dimension(26, 26));
        jToggleButton11.setMinimumSize(new java.awt.Dimension(26, 26));
        jToggleButton11.setPreferredSize(new java.awt.Dimension(26, 26));
        jToggleButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton11ActionPerformed(evt);
            }
        });

        add(jToggleButton11);

        jToggleButton12.setText("4");
        jToggleButton12.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton12.setMaximumSize(new java.awt.Dimension(26, 26));
        jToggleButton12.setMinimumSize(new java.awt.Dimension(26, 26));
        jToggleButton12.setPreferredSize(new java.awt.Dimension(26, 26));
        jToggleButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton12ActionPerformed(evt);
            }
        });

        add(jToggleButton12);

        jToggleButton13.setText("3");
        jToggleButton13.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton13.setMaximumSize(new java.awt.Dimension(26, 26));
        jToggleButton13.setMinimumSize(new java.awt.Dimension(26, 26));
        jToggleButton13.setPreferredSize(new java.awt.Dimension(26, 26));
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });

        add(jToggleButton13);

        jToggleButton14.setText("2");
        jToggleButton14.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton14.setMaximumSize(new java.awt.Dimension(26, 26));
        jToggleButton14.setMinimumSize(new java.awt.Dimension(26, 26));
        jToggleButton14.setPreferredSize(new java.awt.Dimension(26, 26));
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton14ActionPerformed(evt);
            }
        });

        add(jToggleButton14);

        jToggleButton15.setText("1");
        jToggleButton15.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton15.setMaximumSize(new java.awt.Dimension(26, 26));
        jToggleButton15.setMinimumSize(new java.awt.Dimension(26, 26));
        jToggleButton15.setPreferredSize(new java.awt.Dimension(26, 26));
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton15ActionPerformed(evt);
            }
        });

        add(jToggleButton15);

        jToggleButton16.setText("0");
        jToggleButton16.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jToggleButton16.setMaximumSize(new java.awt.Dimension(26, 26));
        jToggleButton16.setMinimumSize(new java.awt.Dimension(26, 26));
        jToggleButton16.setPreferredSize(new java.awt.Dimension(26, 26));
        jToggleButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton16ActionPerformed(evt);
            }
        });

        add(jToggleButton16);

    }//GEN-END:initComponents
    
    private void jToggleButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton16ActionPerformed
        // Add your handling code here:
        if(jToggleButton16.isSelected() == true) {
            mask |= 0x0001;
        } else {
            mask &= 0xfffe;
        }
    }//GEN-LAST:event_jToggleButton16ActionPerformed
    
    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
        // Add your handling code here:
        if(jToggleButton15.isSelected() == true) {
            mask |= 0x0002;
        } else {
            mask &= 0xfffd;
        }
    }//GEN-LAST:event_jToggleButton15ActionPerformed
    
    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        // Add your handling code here:
        if(jToggleButton14.isSelected() == true) {
            mask |= 0x0004;
        } else {
            mask &= 0xfffb;
        }
    }//GEN-LAST:event_jToggleButton14ActionPerformed
    
    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        // Add your handling code here:
        if(jToggleButton13.isSelected() == true) {
            mask |= 0x0008;
        } else {
            mask &= 0xfff7;
        }
    }//GEN-LAST:event_jToggleButton13ActionPerformed
    
    private void jToggleButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton12ActionPerformed
        // Add your handling code here:
        if(jToggleButton12.isSelected() == true) {
            mask |= 0x0010;
        } else {
            mask &= 0xffef;
        }
    }//GEN-LAST:event_jToggleButton12ActionPerformed
    
    private void jToggleButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton11ActionPerformed
        // Add your handling code here:
        if(jToggleButton11.isSelected() == true) {
            mask |= 0x0020;
        } else {
            mask &= 0xffdf;
        }
    }//GEN-LAST:event_jToggleButton11ActionPerformed
    
    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        // Add your handling code here:
        if(jToggleButton10.isSelected() == true) {
            mask |= 0x0040;
        } else {
            mask &= 0xffbf;
        }
    }//GEN-LAST:event_jToggleButton10ActionPerformed
    
    private void jToggleButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton9ActionPerformed
        // Add your handling code here:
        if(jToggleButton9.isSelected() == true) {
            mask |= 0x0080;
        } else {
            mask &= 0xff7f;
        }
    }//GEN-LAST:event_jToggleButton9ActionPerformed
    
    private void jToggleButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton8ActionPerformed
        // Add your handling code here:
        if(jToggleButton8.isSelected() == true) {
            mask |= 0x0100;
        } else {
            mask &= 0xfeff;
        }
    }//GEN-LAST:event_jToggleButton8ActionPerformed
    
    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
        // Add your handling code here:
        if(jToggleButton7.isSelected() == true) {
            mask |= 0x0200;
        } else {
            mask &= 0xfdff;
        }
    }//GEN-LAST:event_jToggleButton7ActionPerformed
    
    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // Add your handling code here:
        if(jToggleButton6.isSelected() == true) {
            mask |= 0x0400;
        } else {
            mask &= 0xfbff;
        }
    }//GEN-LAST:event_jToggleButton6ActionPerformed
    
    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // Add your handling code here:
        if(jToggleButton5.isSelected() == true) {
            mask |= 0x0800;
        } else {
            mask &= 0xf7ff;
        }
    }//GEN-LAST:event_jToggleButton5ActionPerformed
    
    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // Add your handling code here:
        if(jToggleButton4.isSelected() == true) {
            mask |= 0x1000;
        } else {
            mask &= 0xefff;
        }
    }//GEN-LAST:event_jToggleButton4ActionPerformed
    
    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // Add your handling code here:
        if(jToggleButton3.isSelected() == true) {
            mask |= 0x2000;
        } else {
            mask &= 0xdfff;
        }
    }//GEN-LAST:event_jToggleButton3ActionPerformed
    
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // Add your handling code here:
        if(jToggleButton2.isSelected() == true) {
            mask |= 0x4000;
        } else {
            mask &= 0xbfff;
        }
    }//GEN-LAST:event_jToggleButton2ActionPerformed
    
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // Add your handling code here:
        if(jToggleButton1.isSelected() == true) {
            mask |= 0x8000;
        } else {
            mask &= 0x7fff;
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
    
}
