/***********************************************************
 * Software: instrument client
 * Module:   device template class
 * Version:  0.1
 * Licence:  GPL2
 *
 * Owner: Kim Kristo
 * Date creation : 14.9.2012
 *
 ***********************************************************/

package components;

import interfaces.MessageCallbackInterface;
import interfaces.MessageInterface;
import java.util.Hashtable;
import org.apache.log4j.Logger;
import yami.ParamSet;


public class Device_template extends javax.swing.JInternalFrame implements MessageCallbackInterface {
    //private MessageInterface msgIf;
    private static Logger logger;
    private DeviceMessage message;
    
    private String MessageName;
    private String MessageReset = "Reset";
    private String MessageTest = "Test";
    
    /** Creates new form HP54600 */
    public Device_template(String name, Hashtable<String, String>properties, MessageInterface msg) {                
        // get logger instance for this class
        logger = Logger.getLogger(Device_template.class);
        // save messaging context        
        message = new DeviceMessage(name, msg);
        // add message listener
        message.addMessageCallback(name, this);
        
        initComponents();                
    }
    
    /** Function sends message
     *
     * @param param message parameters
     *
     * @return true/false
     *
     */
    
    public boolean DataStreamCallback(ParamSet param) {
        return(true);
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setVisible(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
