/***********************************************************
 * Software: instrument client
 * Module:   intrument tool box class
 * Version:  0.1
 * Licence:  GPL2
 *
 * Owner: Kim Kristo
 * Date creation : 23.10.2012
 *
 ***********************************************************/

package components;

public class InstrumentBox extends javax.swing.JInternalFrame {
    
    /** Creates new form InstrumentBox */
    public InstrumentBox(String name) {
        initComponents();
        this.setTitle(name);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(146, 164, 210));
        setTitle("title");
        setAutoscrolls(true);
        setMaximumSize(new java.awt.Dimension(160, 400));
        setMinimumSize(new java.awt.Dimension(160, 400));
        setPreferredSize(new java.awt.Dimension(160, 400));
        setVisible(true);
        getContentPane().setLayout(new java.awt.FlowLayout());

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
