package components;
/*
 * mapWait.java
 *
 * Created on December 6, 2003, 6:15 PM
 */

/**
 *
 * @author  operator
 */

import java.awt.*;

public class waitDialog extends javax.swing.JFrame {
    
    /** Creates new form mapWait */
    public waitDialog() {
        initComponents();
        setSize(240,80);

    }      
  
    public void setProgress(int p) {
        // set new value to progress bar
        jProgressBar1.setValue(p);
        this.repaint();
    }
    
    public void paint(Graphics g) {
        update(g);
    }
    
    public void update(Graphics g) {
        printAll(g);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jProgressBar1 = new javax.swing.JProgressBar();

        getContentPane().setLayout(new java.awt.FlowLayout());

        setTitle("Hold on...");
        setLocationRelativeTo(this);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jProgressBar1.setDoubleBuffered(true);
        jProgressBar1.setStringPainted(true);
        getContentPane().add(jProgressBar1);

        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    //    new mapWait().show();
    //}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
