/***********************************************************
 * Software: instrument client
 * Module:   HP3488 instrument instances managing class
 * Version:  0.1
 * Licence:  GPL2
 *
 * Owner: Kim Kristo
 * Date creation : 23.10.2012
 *
 ***********************************************************/
package instruments.hp3488;

import components.InstanceBase;
import components.XmlReader;
import components.XmlWriter;
import interfaces.*;
import org.apache.log4j.Logger;
import instruments.*;
import java.util.Hashtable;
import javax.swing.ImageIcon;
import murlen.util.fscript.FSExtension;

public class HP3480Instance extends InstanceBase {

    private MessageInterface msg;

    /** Creates new form HP3480Instance */
    public HP3480Instance(String name, Hashtable<String, String> properties,
            DesktopInterface desktop, MessageInterface msg) {
        // get logger instance for this class
        logger = Logger.getLogger(HP3480Instance.class);

        this.desktop = desktop;
        this.msg = msg;
        this.name = name;

        initComponents();

        // set default icon
        java.net.URL imageURL = this.getClass().getResource("/resources/64x64_signal_generator_2.png");

        // load icon image
        if (imageURL != null) {
            image = new ImageIcon(imageURL);
            this.setIcon(image);
        }

        // create measurement device ui
        device = new HP3480(name, properties, msg);
        // create command interface for scripting
        scriptExtension = new HP3488Extension((commandExecutionInterface) device);
    }

    @Override
    public FSExtension getScriptExtension() {
        return (scriptExtension);
    }

    /** Function implements custom xml handler
     * 
     * @param r instance of XmlReader
     */
    @Override
    public void loadConfig(XmlReader r) {
        // load scope settings
        ((HP3480) device).loadSettings(r);
    }

    /** Function implements prototype of custom xml writer
     * 
     * @param w instance of XmlWriter
     */
    @Override
    public void saveConfig(XmlWriter w) {
        // save scope settings
        ((HP3480) device).saveSettings(w);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setToolTipText("HP3488 Switching contol unit");
        setPreferredSize(new java.awt.Dimension(64, 80));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        mouseClicked(evt);
    }//GEN-LAST:event_formMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
