/***********************************************************
 * Software: instrument client
 * Module:   Scope channel controls class
 * Version:  0.1
 * Licence:  GPL2
 *
 * Owner: Kim Kristo
 * Date creation : 9.1.2013
 *
 ***********************************************************/

package instruments.hp54600;

import components.DeviceMessage;
import oh3ebf.lib.ui.comboboxes.ControlledComboBoxItem;
import oh3ebf.lib.ui.comboboxes.ControlledComboBoxRenderer;


public class ChannelControls extends javax.swing.JPanel {
    private DeviceMessage DevMsg = null;
    private int channel = 0;
    private Object[] probeItems= { new ControlledComboBoxItem("X1"), new ControlledComboBoxItem("X10"),
        new ControlledComboBoxItem("X20", false), new ControlledComboBoxItem("X100")  };
    
    private static final String MessageChannelBwLimit = "ChannelBwLimit";
    private static final String MessageChannelCoupling = "ChannelCoupling";
    private static final String MessageChannelProbe = "ChannelProbe";
    private static final String MessageChannelInvert = "ChannelInvert";
    private static final String MessageChannelVernier = "ChannelVernier";
    
    /** Creates new form ChannelControls */
    public ChannelControls(int ch, DeviceMessage m) {
        this.setName("Ch" + ch);
        channel = ch;
        DevMsg = m;
                                         
        initComponents();        
    }
    
    /** Function returns bandwidth limit 
     * 
     * @return bw limit selection
     */
    
    public int getBwLimit() {
        return(bwLimitComboBox.getSelectedIndex());
    }
    
    /** Function set bandwidth limit
     * 
     * @param index of bw limit value
     */
    
    public void setBwLimit(int index) {
        bwLimitComboBox.setSelectedIndex(index);
    }
        
    /** Function returns channel coupling
     * 
     * @return coupling selection
     */
    
    public int getCoupling() {
        return(couplingComboBox.getSelectedIndex());
    }
    
    /** Function set channel coupling
     * 
     * @param index of coupling
     */
    
    public void setCoupling(int index) {
        couplingComboBox.setSelectedIndex(index);
    }
    
    /** Function returns channel invert selection
     * 
     * @return invert selection
     */
    
    public int getInvert() {
        return(invertComboBox.getSelectedIndex());
    }
    
    /** Function set channel invert
     * 
     * @param index of invert
     */
    
    public void setInvert(int index) {
        invertComboBox.setSelectedIndex(index);
    }
    
    /** Function returns channel vernier selection
     * 
     * @return vernier selection
     */
    
    public int getVernier() {
        return(vernierComboBox.getSelectedIndex());
    }
    
    /** Function set channle vernier
     * 
     * @param index of vernier
     */
    
    public void setVernier(int index) {
        vernierComboBox.setSelectedIndex(index);
    }
    
    /** Function returns channel probe selection
     * 
     * @return probe selection
     */
    
    public int getProbe() {
        return(probeComboBox.getSelectedIndex());
    }
    
    /** Function set channel probe
     * 
     * @param index probe selection
     */
    
    public void setProbe(int index) {
        probeComboBox.setSelectedIndex(index);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bwLimitComboBox = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        probeComboBox = new javax.swing.JComboBox(probeItems);
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        couplingComboBox = new javax.swing.JComboBox();
        invertComboBox = new javax.swing.JComboBox();
        vernierComboBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(196, 204, 223));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bwLimitComboBox.setFont(new java.awt.Font("SansSerif", 0, 10));
        bwLimitComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OFF", "ON" }));
        bwLimitComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bwLimitComboBoxActionPerformed(evt);
            }
        });
        add(bwLimitComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 70, 80, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 35, 140, 5));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 10));
        jLabel2.setText("BW limit");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 73, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 10));
        jLabel1.setText("Coupling");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 10, -1, 20));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 10));
        jLabel3.setText("Invert");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 103, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 10));
        jLabel4.setText("Vernier");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 133, -1, -1));

        probeComboBox.setFont(new java.awt.Font("SansSerif", 0, 10));
        probeComboBox.setRenderer(new ControlledComboBoxRenderer());
        probeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probeComboBoxActionPerformed(evt);
            }
        });
        add(probeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 40, 80, 20));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 10));
        jLabel5.setText("Probe");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 43, -1, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 140, 5));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 95, 140, 5));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 125, 140, 5));

        couplingComboBox.setFont(new java.awt.Font("SansSerif", 0, 10));
        couplingComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "DC", "GND" }));
        couplingComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couplingComboBoxActionPerformed(evt);
            }
        });
        add(couplingComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 10, 80, 20));

        invertComboBox.setFont(new java.awt.Font("SansSerif", 0, 10));
        invertComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OFF", "ON" }));
        invertComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invertComboBoxActionPerformed(evt);
            }
        });
        add(invertComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 100, 80, 20));

        vernierComboBox.setFont(new java.awt.Font("SansSerif", 0, 10));
        vernierComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "OFF", "ON" }));
        vernierComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vernierComboBoxActionPerformed(evt);
            }
        });
        add(vernierComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 130, 80, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void bwLimitComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bwLimitComboBoxActionPerformed
        // set band width limit
        if(DevMsg != null) {
            DevMsg.sendComboBoxSelection(MessageChannelBwLimit, channel, bwLimitComboBox);
        }
}//GEN-LAST:event_bwLimitComboBoxActionPerformed

    private void couplingComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couplingComboBoxActionPerformed
        // set band width limit
        if(DevMsg != null) {
            DevMsg.sendComboBoxSelection(MessageChannelCoupling, channel, couplingComboBox);
        }
}//GEN-LAST:event_couplingComboBoxActionPerformed

    private void invertComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invertComboBoxActionPerformed
        // set band width limit
        if(DevMsg != null) {
            DevMsg.sendComboBoxSelection(MessageChannelInvert, channel, invertComboBox);
        }
}//GEN-LAST:event_invertComboBoxActionPerformed

    private void vernierComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vernierComboBoxActionPerformed
        // set band width limit
        if(DevMsg != null) {
            DevMsg.sendComboBoxSelection(MessageChannelVernier, channel, vernierComboBox);
        }
}//GEN-LAST:event_vernierComboBoxActionPerformed

    private void probeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_probeComboBoxActionPerformed
        // set band width limit
        if(DevMsg != null) {
            DevMsg.sendComboBoxSelection(MessageChannelProbe, channel, probeComboBox);
        }
    }//GEN-LAST:event_probeComboBoxActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox bwLimitComboBox;
    private javax.swing.JComboBox couplingComboBox;
    private javax.swing.JComboBox invertComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JComboBox probeComboBox;
    private javax.swing.JComboBox vernierComboBox;
    // End of variables declaration//GEN-END:variables
    
}
